(def bob-too-bad [
  "Sadder than a map!"
  "A blamed pity."
  "Oh, {p:he's} in a bad loaf now."
  "Well, that's how the cookie crumbles."
  "Better {p:him} than me."
  "Sic semper contestantus."
  "Epic fail!"
  "TS."
  "Tough darts."
  "Ain't that a bite!"
  "Miz!"
  "Nebekh!"
  "Très bummer."
  "Sad trombone."
  "Oh, I'm sorry!"
  "The agony of defeat!"
  "Shazbot!"
  "Press F to pay respects."])
